// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenMgmt.Server.Persistence.Repository;

namespace penmgmt.server.api.Migrations
{
    [DbContext(typeof(PenMgmtContext))]
    [Migration("20190605141010_ModifyPartMaster")]
    partial class ModifyPartMaster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PenMgmt.Common.Domain.PartMaster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Committed");

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.ToTable("PartMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
